config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :links
  resources :views, path: :view, only: [:show]
  root "links#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/link.rb
class Link < ApplicationRecord
    has_many :views, dependent: :destroy

    scope :recent_first, -> { order(created_at: :desc) }
    
    validates :url, presence: true

    after_save_commit if: :url_previously_changed? do 
        MetadataJob.perform_later(to_param)
    end

    def self.find_by_short_code(code)
        find ShortCode.decode(code)
    end
    
    def to_param
        ShortCode.encode(id)
    end

    def domain
        URI(url).host rescue URI::InvalidURIError
    end
  end
  

app/models/metadata.rb
require "open-uri"

class Metadata
  attr_reader :doc
  def self.retrieve_from(url)
    new (URI.open(url))
  rescue StandardErrror
    new
  end 

  def initialize(html=nil)
    @doc = Nokogiri::HTML(html)
  end

  def attributes
    {
      title: title,
      description: description,
      image: image
    }
  end

  def title 
    doc.at_css("title")&.text
  end

  def description
    meta_tag_content "description"
  end

  def image
    meta_tag_content "og:image", name_attribute: :property
  end

  def meta_tag_content(name, name_attribute: :name)
    doc.at_css("meta[#{name_attribute}='#{name}']")&.attributes&.fetch("content", nil)&.text
  end
end

app/models/short_code.rb
class ShortCode
  ALPHABET = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ".freeze
  BASE = ALPHABET.length

  def self.encode(number)
    raise ArgumentError, "Number must be a non-negative integer" unless number.is_a?(Integer) && number >= 0

    return ALPHABET[0] if number.zero?

    result = ""
    while number.positive?
      result << ALPHABET[number % BASE]
      number /= BASE
    end

    result.reverse
  end

  def self.decode(string)
    raise ArgumentError, "Input must be a non-empty string with valid characters" unless valid_string?(string)

    string.each_char.reduce(0) do |number, char|
      number * BASE + ALPHABET.index(char)
    end
  end


  private

  def self.valid_string?(string)
    string.is_a?(String) && !string.empty? && string.chars.all? { |char| ALPHABET.include?(char) }
  end

end

app/models/view.rb
class View < ApplicationRecord
  belongs_to :link, counter_cache: true

  def location
    Geocoder.search(ip).first
  end

  def city
    location.city if location
  end

  def country
    location.country if location
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include Pagy::Backend

    def set_link
        @link = Link.find_by_short_code(params[:id])
    end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController 
    before_action :set_link, only: [:show, :update, :destroy]

    def index
        @pagy, @links = pagy(Link.recent_first, items: 10)
        @link ||= Link.new
    rescue Pagy::OverflowError
        redirect_to root_path
    end
  
    def create 
      @link = Link.new(link_params)
      if @link.save
        respond_to do |format|
            format.html {redirect_to root_path }
            format.turbo_stream { render turbo_stream: turbo_stream.prepend("links", @link)}
        end
      else
        index
        render :index, status: :unprocessable_entity
      end
    end

    def show
        @pagy, @views = pagy(@link.views.order(created_at: :desc), items: 10)
    end
  
    def update
      if @link.update(link_params)
        redirect_to @link
      else
        render :edit, status: unprocessable_entity
      end
    end
  
    def destroy
      @link.destroy
      redirect_to root_path, notice: "Link has been deleted."
    end
  
    private 
  
    def link_params
      params.require(:link).permit(:url)
    end
  end

app/controllers/views_controller.rb
class ViewsController < ApplicationController
    before_action :set_link
  
    rescue_from ActiveRecord::RecordNotFound do
        redirect_to root_path, alert: "Missing Link!"
    end

    def show
      @link.views.create(ip: request.ip, user_agent: request.user_agent)
      redirect_to @link.url, allow_other_host: true
    end
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
    include Pagy::Frontend
end

app/helpers/favicon_helper.rb
module FaviconHelper
    def favicon_image_tag(domain, **kwargs)
      image_tag google_favicon_url(domain), **kwargs
    end
    def google_favicon_url(domain)
      "https://www.google.com/s2/favicons?domain=#{domain}"
    end
  end
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UrlShortener</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <script src="https://unpkg.com/@popperjs/core@2"></script>
    <script src="https://unpkg.com/tippy.js@6"></script>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="px-5 mx-auto prose mt-28">
      <%= tag.p alert, class: "px-4 py-2 text-sm font-medium text-yellow-800 bg-yellow-100 rounded" if alert%>
      <%= tag.p notice, class: "px-4 py-2 text-sm font-medium text-blue-800 bg-blue-100 rounded" if notice%>
      <%= yield %>
    </main>
  </body>
</html>

app/views/links/_form.html.erb
<%= form_with model: link, data: {controller: "reset-form", action: "turbo:submit-end->reset-form#reset"} do |form|%>
    <div class="flex items-center gap-2 my-4">
        <%=  form.url_field :url, required: true, autofocus:true, placeholder: "https://google.com", class: "flex-grow rounded"%>
        <%= form.button "Shorten URL", class: "px-7 py-2 bg-green-500 rounded text-white"%>
    </div>
<% end %>

app/views/links/_link.html.erb
<%= tag.div id: dom_id(link) do %>
    <%= turbo_stream_from link %>

    <div class="grid items-center grid-cols-8 gap-4 p-4 border-2 border-gray-400 rounded">

        <div class="flex flex-row items-center col-span-6 gap-4">
            <%= favicon_image_tag link.domain, class: "inline-block size-5" %>
            <div class="flex flex-col gap-2">
                <%= link.title || link.url %>
                <%= tag.div link.description, class: "text-xs text-gray-700" %>
            </div>
        </div>

        <div class="flex items-center justify-center w-12 h-8 text-xs text-center" >
            <%= pluralize(link.views_count, "view") %>
        </div>
        <div class="flex flex-col gap-4">
            <div class="flex items-center justify-center w-full h-8 text-xs bg-green-500 rounded">
                <%= link_to "Report", link, class: "no-underline flex items-center justify-center h-8 w-full text-white" %>
            </div>

            <div class="text-xs">
                <%= link_to view_path(link), target: :_blank, data: { turbo: false }, class: "no-underline flex justify-center items-center rounded bg-green-500 text-white h-8 w-full" do %>
                    <span>Visit</span>
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="white" class="size-4">
                        <path fill-rule="evenodd" d="M12.97 3.97a.75.75 0 0 1 1.06 0l7.5 7.5a.75.75 0 0 1 0 1.06l-7.5 7.5a.75.75 0 1 1-1.06-1.06l6.22-6.22H3a.75.75 0 0 1 0-1.5h16.19l-6.22-6.22a.75.75 0 0 1 0-1.06Z" clip-rule="evenodd" />
                    </svg>
                <% end %>
            </div>
            <%= button_tag class: "flex items-center justify-center w-full h-8 bg-green-500 rounded", data: {controller: "clipboard", clipboard_text: view_url(link)} do %>
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="white" class="size-4">
                    <path fill-rule="evenodd" d="M18.97 3.659a2.25 2.25 0 0 0-3.182 0l-10.94 10.94a3.75 3.75 0 1 0 5.304 5.303l7.693-7.693a.75.75 0 0 1 1.06 1.06l-7.693 7.693a5.25 5.25 0 1 1-7.424-7.424l10.939-10.94a3.75 3.75 0 1 1 5.303 5.304L9.097 18.835l-.008.008-.007.007-.002.002-.003.002A2.25 2.25 0 0 1 5.91 15.66l7.81-7.81a.75.75 0 0 1 1.061 1.06l-7.81 7.81a.75.75 0 0 0 1.054 1.068L18.97 6.84a2.25 2.25 0 0 0 0-3.182Z" clip-rule="evenodd" />
                </svg>
            <% end %>
        </div>
    </div>
<% end %>

app/views/links/_views_list.html.erb
<h3>Views List</h3>
<ul class="text-xs">
  <% @views.each do |view| %>
    <li>
      <strong>User Agent:</strong> <%= view.user_agent %><br>
      <strong>IP Address:</strong> <%= view.ip %><br>
      <strong>City:</strong> <%= view.city || 'Unknown' %><br>
      <strong>Country:</strong> <%= view.country || 'Unknown' %><br>
      <strong>Viewed At:</strong> <%= view.created_at %>
    </li>
  <% end %>
</ul>
<% if @pagy.pages > 1 %>
    <div class="pt-8 mb-16 text-center">
        <%== pagy_nav(@pagy, link_extra: 'data-turbo-frame="views-list"') %>
    </div>
<% end %>

app/views/links/index.html.erb
<div class="flex items-center gap-4">
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="size-8">
        <path fill-rule="evenodd" d="M18.97 3.659a2.25 2.25 0 0 0-3.182 0l-10.94 10.94a3.75 3.75 0 1 0 5.304 5.303l7.693-7.693a.75.75 0 0 1 1.06 1.06l-7.693 7.693a5.25 5.25 0 1 1-7.424-7.424l10.939-10.94a3.75 3.75 0 1 1 5.303 5.304L9.097 18.835l-.008.008-.007.007-.002.002-.003.002A2.25 2.25 0 0 1 5.91 15.66l7.81-7.81a.75.75 0 0 1 1.061 1.06l-7.81 7.81a.75.75 0 0 0 1.054 1.068L18.97 6.84a2.25 2.25 0 0 0 0-3.182Z" clip-rule="evenodd" />
    </svg>
    <h1 class="my-4 text-4xl font-extrabold leading-none tracking-tight text-gray-900">Shorten a long URL</h1>
</div>

<%= render partial: "form", locals: {link: @link} %>

<div id="links"  class="flex flex-col gap-4">
    <%= render @links %>
        <% if @pagy.pages > 1 %>
        <div class="pt-8 mb-16 text-center">
            <%== pagy_nav @pagy %>
        </div>
    <% end %>
</div>

app/views/links/show.html.erb
<div class="flex items-center justify-between text-xs">
    <%= link_to "← Back to all links", root_path, class: "no-underline text-xs px-3 py-2 rounded bg-green-500 text-white"%>
    <div class="flex items-center gap-4">
        <%= tag.div pluralize(@link.views_count, "view"), class: "w-20 h-8 flex items-center font-semibold" %>
        <%= button_tag class: "flex items-center justify-center w-12 h-8 bg-green-500 rounded", data: {controller: "clipboard", clipboard_text: view_url(@link)} do %>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="white" class="size-4">
                <path fill-rule="evenodd" d="M18.97 3.659a2.25 2.25 0 0 0-3.182 0l-10.94 10.94a3.75 3.75 0 1 0 5.304 5.303l7.693-7.693a.75.75 0 0 1 1.06 1.06l-7.693 7.693a5.25 5.25 0 1 1-7.424-7.424l10.939-10.94a3.75 3.75 0 1 1 5.303 5.304L9.097 18.835l-.008.008-.007.007-.002.002-.003.002A2.25 2.25 0 0 1 5.91 15.66l7.81-7.81a.75.75 0 0 1 1.061 1.06l-7.81 7.81a.75.75 0 0 0 1.054 1.068L18.97 6.84a2.25 2.25 0 0 0 0-3.182Z" clip-rule="evenodd" />
            </svg>
        <% end %>
    </div>
</div>

<h1 class="mt-4"><%= @link.url %></h1>
<%= tag.div @link.description %>
<%= link_to view_path(@link), target: :_blank, data: {turbo: false}, class: "text-xs px-3 py-1.5 rounded bg-green-500 no-underline text-white" do%>
    <%= favicon_image_tag @link.domain, class: "inline-block" %>
    <%= truncate @link.url %>
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="inline-block size-4">
        <path fill-rule="evenodd" d="M12.97 3.97a.75.75 0 0 1 1.06 0l7.5 7.5a.75.75 0 0 1 0 1.06l-7.5 7.5a.75.75 0 1 1-1.06-1.06l6.22-6.22H3a.75.75 0 0 1 0-1.5h16.19l-6.22-6.22a.75.75 0 0 1 0-1.06Z" clip-rule="evenodd" />
    </svg>
<% end %>

<%= line_chart @link.views.group_by_day(:created_at, range: 2.weeks.ago..Time.now, expand_range: true).count %>

<turbo-frame id="views-list">
  <%= render 'views_list', link: @link %>
</turbo-frame>